### ISSUE TITLE
Feature Request - Web API

### ISSUE THREAD

**Issue by 2BWorks** [itsthejoker/filamentcolors.xyz#1]
Hey! 

Love your work, i think it would be a great addition if filamentcolors would have a public facing web api. The features would be completly the same as the website just without any UI.

Full disclose: I'm asking for this feature because I'm planning some cool features in the 3D Geeks app that would benefit this API. If you want i can contribute, however my python knowledge is minmal. Maybe we can discuss something privately so i can create the API in ktor for example. I would just need access to the mysql or postgres that you are using.

Toby

**Comment by itsthejoker** [comment]
I'll dust off the old attempt at an API and see how much effort (if any) would be required to bring it up to snuff. I'm totally fine with my work being used for your app, I just ask that you provide some kind of byline about the site ("colors from filamentcolors.xyz" or something along those lines, maybe?).

Either way, I can take a look at it this weekend :)

**Comment by 2BWorks** [comment]
Hey Joe,

No doubt, a clickable: “Powered by: filamentcolors.xyz” will be there for sure! If I can be of any assistance let me know!

Cheers

**Comment by itsthejoker** [comment]
Done and live! See readme for information on accessing. Feel free to ping me if you have any questions and please don't swamp my poor (very cheap) server 😆 

Cheers -- gonna close this issue just because this feature is complete.
