### ISSUE TITLE
Spectrometry information.

### ISSUE THREAD

**Issue by adamwespiser** [itsthejoker/filamentcolors.xyz#108]
Great Project!

I'm doing a project with subtractive mixing and 3d printing, and had two question regarding this project:

1) How are the measurements for filaments being done? I understand from the readme it's done via spectrum analyzer and conversion to RGB, but what device is being used for this?
2) Is it possible to add the spectrum data to the website, or somehow transfer the data to me?

Thanks for the website!

**Comment by itsthejoker** [comment]
Hi, Adam!

I use the [Datacolor ColorReader spectrophotometer](https://www.datacolor.com/colorreader/products/colorreader/) currently. We don't currently record all of the values; just the RGB values reported by the tool at this time.

We're in the process of upgrading to an actual professional benchtop spectrophotometer that will allow easy export of this data, and once we get it, we'll remeasure the entire library, record this data, and make it available. For now though, the RGB values are the best I can provide.

Cheers!

**Comment by adamwespiser** [comment]
Thanks for getting back to me!

I'm starting a project to implement: https://github.com/troscianko/OSpRad (just as a hobby). The total costs are much lower than a commercial unit, and I'll let you know if I get it working!
