### ISSUE TITLE
[Suggestion] Coordination with Spoolman project

### ISSUE THREAD

**Issue by Cellivar** [itsthejoker/filamentcolors.xyz#127]
Hello! Your website is delightful and I am overjoyed at the rigor that has gone into your color analysis process. Thank you so much for the work that you're doing.

I've submitted [a feature request to the Spoolman filament tracking project](https://github.com/Donkie/Spoolman/issues/421) to look into pulling color information automatically from your database. I'm presently doing this manually, and deeper integration would of course be very nice to have.

Additionally, the developer behind Spoolman has [started a database of filament information](https://github.com/Donkie/SpoolmanDB) that has at least some overlap with your own. It may be beneficial to the community to coordinate efforts. As someone who's career involves caring about sources of truth and information duplication, I wanted to at least raise this project to your attention as another active project collecting filament data.

**Comment by itsthejoker** [comment]
Hey Cellivar! Thanks for this. I've chatted with @Donkie here: https://github.com/Donkie/Spoolman/discussions/372 — the short version is that they need more information than what I store, so this is definitely a 'nice to have' for Spoolman. I'm happy to contribute any special endpoints or info that they need if they want to use the API.

**Comment by Cellivar** [comment]
Whelp that's what I get for trusting GitHub's search to show me previous discussions! Thanks for following up, sounds like there's nothing more specific to explore right now.
