### ISSUE TITLE
Look into assembling a spectrum palette

### ISSUE THREAD

**Issue by adamjameshuston** [itsthejoker/filamentcolors.xyz#16]
one spectrum: a rainbow

less constraints: gradients

[a quick google](https://stackoverflow.com/questions/54247946/how-to-generate-a-series-of-hex-codes-in-rainbow-order-given-a-counter)

It might be an incredibly difficult computing task involving comparing to a dynamic array or it might be something you can cheat with your existing "sort by hue" functions

**Comment by itsthejoker** [comment]
After doing a lot of thinking about it, I think that the best that we're going to reasonably accomplish is the existing sort by color method here: https://filamentcolors.xyz/library/sort/color/
