### ISSUE TITLE
FR: Web API: Database version config call that indicates changes

### ISSUE THREAD

**Issue by tobyworks** [itsthejoker/filamentcolors.xyz#3]
It would be nice to have some sort of database versioning. So you can make a simple call and check if the data you have previously persisted is the most up to date data. This would really improve the performance of an implementing app, and also highly reduce the server load when the implementing party has implemented this check correctly.

Example call:
```
GET https://www.filamentcolors.xyz/api/version
```
Example response:
```
{ "database_version": 12, "database_last_modified": 1581427506 // timestamp in seconds }
```

**Comment by tobybonhof** [comment]
Example response:

`{
"database_version": 12,
"database_last_modified": 1581427506 // timestamp in seconds
}`

**Comment by itsthejoker** [comment]
I've actually never heard of this. That's a great idea -- I'll look into it!

**Comment by itsthejoker** [comment]
Implemented and will be available in the next deploy.

**Comment by itsthejoker** [comment]
This is live at https://www.filamentcolors.xyz/api/version/ !
