### ISSUE TITLE
Bug: Too many redirects when opening front or back picture of swatches

### ISSUE THREAD

**Issue by 2BWorks** [itsthejoker/filamentcolors.xyz#5]
![image](https://user-images.githubusercontent.com/45271986/74257542-482f9d80-4cf5-11ea-830b-67da542362ba.png)

As shown in the screenshot above

**Comment by 2BWorks** [comment]
*update*:
Also happens on some pages on the webstie:

![image](https://user-images.githubusercontent.com/45271986/74258387-84173280-4cf6-11ea-83ca-ef1b4b484b77.png)


Maybe this has to do with the recent changes you've done with the www. redirection

**Comment by itsthejoker** [comment]
I can't replicate it; tried on mobile Chrome, desktop Chrome and Firefox. Does clearing your cookies work?

**Comment by 2BWorks** [comment]
Clearing cookies did not work, even tried it in incognito, will try again in an hour or so. I'll update this thread once I've done soOn Feb 11, 2020 18:09, Joe Kaufeld <notifications@github.com> wrote:I can't replicate it; tried on mobile Chrome, desktop Chrome and Firefox. Does clearing your cookies work?

**Comment by itsthejoker** [comment]
Weird, okay. I'll try again later as well. If you're still seeing the issue later, please post a few links that don't work for you so that I can check the logs.

**Comment by 2BWorks** [comment]
Sure thing!On Feb 11, 2020 18:14, Joe Kaufeld <notifications@github.com> wrote:Weird, okay. I'll try again later as well. If you're still seeing the issue later, please post a few links that don't work for you so that I can check the logs.

**Comment by 2BWorks** [comment]
Ok so i have tried again in a new incognito tab and it still happens.

One of the images that isn't working for me is this one:
https://filamentcolors.xyz/media/IMG_20190321_212211_183-front_q1rWSXx.jpg
https://filamentcolors.xyz/media/IMG_20190321_212211_183-back_UdKSgG4.jpg

I have also tried the urls in safari, a browser I never use, so it could not possibly have cookies for filamentcolors.xyz, and it still produces same output

![image](https://user-images.githubusercontent.com/45271986/74266565-c8113400-4d04-11ea-851c-664dc24ee77b.png)

**Comment by itsthejoker** [comment]
I was able to get some of those links you posted to trigger the error and I think I fixed it!

It looks like this was an SSL issue where Cloudflare was fighting my LetsEncrypt cert. I'm going to close this for now because I think it's fixed -- if this happens again, please reopen!

**Comment by 2BWorks** [comment]
Can confirm that it's fixed
